name: publish phone number app

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    env:
      REGISTRY: ghcr.io
      IMAGE_NAMESPACE: geher-marcell
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate image tag
        run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.RW_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/phone-number-backend:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/phone-number-backend:latest

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/phone-number-frontend:${{ env.IMAGE_TAG }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/phone-number-frontend:latest

      - uses: azure/setup-kubectl@v4
        with:
          version: latest
          
      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml

          kubectl set image deployment/phone-number-backend-deployment \
          phone-number-backend=ghcr.io/geher-marcell/phone-number-backend:${{ env.IMAGE_TAG }}

          kubectl set image deployment/phone-number-frontend-deployment \
          phone-number-frontend=ghcr.io/geher-marcell/phone-number-frontend:${{ env.IMAGE_TAG }}